### ISSUE TITLE
add selected item details feature

### ISSUE THREAD

**Issue by derekeder** [datamade/CartoTemplate#8]
We can make this optional, but it would be good to add the scaffolding for selecting an item on the map, like this:

<img width="1129" alt="screen shot 2016-10-11 at 10 42 30 am" src="https://cloud.githubusercontent.com/assets/919583/19277505/823859b6-8f9f-11e6-9956-b4a8fc45c169.png">

**Comment by reginafcompton** [comment]
Also, add an optional "featureClick" function for modal pop.
